Better error message for test that should panic but passes
foundry-rs/starknet-foundry pull request #1551
Opened 2024-01-17 11:08 UTC by Draggu

Closes #1463

## Introduced changes

Added better error message for test that should panic but passes.

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

2024-01-17 11:43 UTC, drknzz requested changes

2024-01-17 11:43 UTC, drknzz commented on CHANGELOG.md
> +- Error message for test that should panic but passes
```suggestion
- Error message for tests that should panic but pass
```

2024-01-17 11:43 UTC, drknzz commented on crates/forge-runner/src/test_case_summary.rs
> +                ExpectedPanicValue::Any => Some("\n    Expected to panic".into()),
This isn't tested i believe

2024-01-17 12:03 UTC, piotmag769 reviewed
Good job and congrats on your first PR! 🎉 
Add the requested test and it's good to go imo

2024-01-17 12:03 UTC, piotmag769 commented on crates/forge-runner/src/test_case_summary.rs
> +                        "\n    Expected to panic with data\n    Expected:  {panic_data:?} ({panic_string})\n"
```suggestion
                        "\n    Expected to panic but didn't\n    Expected panic data:  {panic_data:?} ({panic_string})\n"
```
[nit]

2024-01-17 12:03 UTC, piotmag769 commented on crates/forge-runner/src/test_case_summary.rs
> +                ExpectedPanicValue::Any => Some("\n    Expected to panic".into()),
```suggestion
                ExpectedPanicValue::Any => Some("\n    Expected to panic but didn't".into()),
```
[nit]

2024-01-17 14:13 UTC, drknzz commented on crates/forge-runner/src/test_case_summary.rs
> +                ExpectedPanicValue::Any => Some("\n    Expected to panic but didn't".into()),
Probably should end with newline for consistency

2024-01-17 14:13 UTC, drknzz commented on crates/forge/tests/e2e/running.rs
> +        [PASS] tests::should_panic_test::should_panic_check_data (gas: ~1)
```suggestion
        [PASS] tests::should_panic_test::should_panic_check_data [..]
```
Let's not assert gas in here

2024-01-17 14:27 UTC, drknzz commented on crates/forge/tests/e2e/running.rs
> +        [PASS] tests::should_panic_test::should_panic_check_data (gas: ~1)
Let's do it in the whole test*, sorry for not clarifying!

2024-01-18 10:48 UTC, piotmag769 approved these changes

2024-01-18 10:48 UTC, piotmag769 commented on crates/forge/tests/e2e/running.rs
>      assert_stdout_contains!(
I know you prob copied the output you got (and it's completely fine), just FYI: this macro doesn't check the order in which lines are printed

2024-01-18 11:12 UTC, drknzz approved these changes
Nicely done, good job 🔥 👍

2024-01-18 12:04 UTC, merged