Delete mention of enabling the casm explicitly
foundry-rs/starknet-foundry pull request #2028
Opened 2024-04-16 14:03 UTC by Arcticae

2024-04-16 18:50 UTC, piotmag769 approved these changes

2024-04-17 07:17 UTC, MaksymilianDemitraszek commented
Have we remove this from the template?

2024-04-17 07:19 UTC, MaksymilianDemitraszek commented
![image](https://github.com/foundry-rs/starknet-foundry/assets/32527780/77b4ab1f-467f-410f-826a-722df9eb360e)
We also could probably remove it from our codebase.

2024-04-17 11:11 UTC, piotmag769 commented
@MaksymilianDemitraszek enabling casm in Scarb.toml is fine, it's just not necessary - if the casm is present we will use it, if not, we will use USC

2024-04-17 13:30 UTC, MaksymilianDemitraszek commented
Imo would be better to have one way to do this.

2024-04-17 18:08 UTC, piotmag769 commented
>Don't see any reason why we would want to consume scarb produced casm.

It is embedded in our logic though (in scarb-api I believe), I remember that I supported this idea. If Scarb already produced casm why should we recompile the sierra?

2024-04-18 09:08 UTC, THenry14 requested changes
Do you mind giving some more context? what is this change related to?

2024-04-18 09:08 UTC, THenry14 commented on crates/sncast/tests/utils/build_contracts.sh
>    exit 1
this file will be removed in https://github.com/foundry-rs/starknet-foundry/pull/2008 as it is no longer needed

2024-04-18 14:15 UTC, piotmag769 commented
>Do you mind giving some more context? what is this change related to?

@THenry14 You don't need the `casm = true` in Scarb since we can compile with USC

https://github.com/foundry-rs/starknet-foundry/blob/master/crates/scarb-api/src/lib.rs#L55

2024-04-18 14:30 UTC, THenry14 commented
> > Do you mind giving some more context? what is this change related to?
> 
> @THenry14 You don't need the `casm = true` in Scarb since we compile contracts with USC when needed
> 
> https://github.com/foundry-rs/starknet-foundry/blob/master/crates/scarb-api/src/lib.rs#L55

ahh, thanks. this is the context I was missing 🙏

2024-04-23 13:32 UTC, merged