Add Verifying Contracts guide
foundry-rs/starknet-foundry pull request #2286
Opened 2024-07-09 10:41 UTC by romanbarbo

## Introduced changes

This Pull Request adds the Verifying Contracts guide for the `verify` command.

## Checklist

- [x] Updated relevant documentation
- [x] Performed self-review of the code

2024-07-09 14:40 UTC, Arcticae requested changes

2024-07-09 14:40 UTC, Arcticae commented on docs/src/starknet/verify.md
> +
I think we should add an explanation what happens next in the flow (where to look for the status)

2024-07-09 14:40 UTC, Arcticae commented on docs/src/starknet/verify.md
> +Starknet Foundry `sncast` supports verifying Cairo contract classes with the `sncast verify` command by submitting the source code to a selected verification provider.
This doesn't explain why you should verify and what it really means

2024-07-09 14:40 UTC, Arcticae commented on docs/src/starknet/verify.md
> +> Please be aware that submitting the source code means it will be publicly exposed through the provider's APIs.
I think it's also worth explaining here what happens to the code on the backend (how it can be used)

2024-07-10 12:01 UTC, barabanovro commented
Thank you for the review. I have addressed the comments

2024-07-10 12:06 UTC, Arcticae requested changes

2024-07-10 12:06 UTC, Arcticae commented on docs/src/starknet/verify.md
> +After verification with Walnut verifier, the contract can be debugged using Walnut's transaction step-by-step debugger.
If this is a general section (see the title marking that you did at `Example`), this does not belong here 

Also i don't think this is relevant at all

2024-07-10 12:06 UTC, Arcticae commented on docs/src/starknet/verify.md
> +After verification with Walnut verifier, the contract can be debugged using Walnut's transaction step-by-step debugger.
It still lacks the explanation where should i look for the confirmation, the "green check mark" that i'm after when doing the verification etc.

Is there a URL that i can use?

2024-07-10 12:42 UTC, Arcticae approved these changes

2024-07-10 12:58 UTC, merged