dev: content specific links for starkscan
foundry-rs/starknet-foundry pull request #2476
Opened 2024-09-17 14:10 UTC by milancermak

## Introduced changes

- Links to StarkScan are now differentiated by type. Instead of the generic `/search/<HASH>`, they go to `/tx/<HASH>`, `/class/<HASH>` or `/contract/<ADDR>`, similar as with Voyager.

## Checklist

- [ ] Linked relevant issue
- [x] Updated relevant documentation
- [ ] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

2024-09-18 12:23 UTC, cptartur approved these changes

2024-09-19 21:14 UTC, integraledelebesgue requested changes
StarkScan interaction is going to change a little bit [here](https://github.com/foundry-rs/starknet-foundry/pull/2466#issue-2522247149). Please wait until this PR gets merged and update your fix then.

2024-09-25 09:51 UTC, milancermak commented
@integraledelebesgue done

2024-09-25 13:53 UTC, integraledelebesgue approved these changes

2024-09-26 11:34 UTC, merged