Add library call syscall test
foundry-rs/starknet-foundry pull request #252
Opened 2023-07-24 09:14 UTC by piotmag769

2023-07-25 14:47 UTC, cptartur requested changes
I think we should test that the delegate call actually behaves like a delegate call: 

1. deploy `Executor` at some address
2. `add_two` should store something in `Executor` contract storage
3. call `add_two` through `Caller` delegate call
4. call `Executor` directly through its dispatcher, verify that the value wasn't actually set

Perhaps even more steps can be added to this for more robust verification, but that's my current idea

2023-07-25 14:47 UTC, cptartur commented on starknet-foundry/crates/forge/tests/integration/syscalls.rs
> +                        )
Nit, but this conversion could be done at test level and here we could just accept `ClassHash`

2023-07-26 10:12 UTC, cptartur approved these changes
👌

2023-07-26 10:12 UTC, cptartur commented on starknet-foundry/crates/forge/tests/integration/syscalls.rs
> +        fn test_increase_balance() {
```suggestion
        fn test_library_call() {
```

2023-07-26 10:54 UTC, Radinyn approved these changes

2023-07-26 12:11 UTC, merged