Remove deprecated LegacyMap
foundry-rs/starknet-foundry pull request #2608
Opened 2024-10-24 19:52 UTC by sprtd

Closes #2598

## Introduced changes

- Replace `LegacyMap` storage mapping with `Map`

## Checklist

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [ ] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

2024-10-24 23:45 UTC, franciszekjob requested changes
Please fix failing tests and formatting and we should be good to go 👍 .

2024-10-24 23:45 UTC, franciszekjob commented on crates/sncast/README.md
Changing readme is not needed.

2024-10-24 23:45 UTC, franciszekjob commented on design_documents/stark_curve_signatures.md
This file shouldn't be changed as well.

2024-10-24 23:45 UTC, franciszekjob commented on design_documents/store_load_cheatcodes.md
These changes are not needed as well.

2024-10-24 23:45 UTC, franciszekjob commented on crates/forge/tests/integration/test_state.rs
> -
No need to remove this line.

2024-10-25 13:22 UTC, franciszekjob requested changes
Please fix failing tests and linting 🙏 .

2024-10-28 16:32 UTC, sprtd commented
@franciszekjob 
these are the failing e2e tests:

```
test e2e::running::detailed_resources_flag ... FAILED
test e2e::running::simple_package_with_git_dependency ... FAILED
test e2e::running::storage_access_default_values ... FAILED 
```

2024-10-29 18:26 UTC, franciszekjob commented
Hi @sprtd, I see the tests are still failing. Did you try to fix them?

2024-10-29 18:35 UTC, sprtd commented
> Hi @sprtd, I see the tests are still failing. Did you try to fix them?

fixed the rest. 
however, `cargo test detailed_resources_flag` fails

2024-10-30 17:34 UTC, franciszekjob approved these changes
LGTM :)

2024-10-30 21:55 UTC, merged