Handle contract redeclaration in cast script
foundry-rs/starknet-foundry pull request #2614
Opened 2024-10-25 15:47 UTC by cptartur

Closes #2469 

## Introduced changes

-

## Checklist

- [ ] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [ ] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

2024-11-07 19:57 UTC, franciszekjob requested changes
Looking good 👍  left some minor remarks.

2024-11-07 19:57 UTC, franciszekjob commented on crates/sncast/tests/e2e/script/declare.rs
> +        "12345",
Is this needed?

2024-11-07 19:57 UTC, franciszekjob commented on crates/sncast/src/main.rs
> +                    unreachable!("Argument skip_on_already_declared is false")
nit:
```suggestion
                    unreachable!("Argument `skip_on_already_declared` is false")
```

2024-11-07 19:57 UTC, franciszekjob commented on crates/sncast/tests/data/scripts/declare/src/same_contract_twice.cairo
> +        DeclareResult::Success(_) => panic!("Should be already declare"),
```suggestion
        DeclareResult::Success(_) => panic!("Should be already declared"),
```

2024-11-08 13:58 UTC, ddoktorski approved these changes

2024-11-09 15:36 UTC, franciszekjob approved these changes
LGTM

2024-11-12 17:49 UTC, merged