Add data transformer examples to docs
foundry-rs/starknet-foundry pull request #2682
Opened 2024-11-18 08:40 UTC by kkawula

Closes #2557

## Introduced changes

-

## Checklist

- [ ] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [ ] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

2024-11-20 12:04 UTC, cptartur requested changes

2024-11-20 12:04 UTC, cptartur commented on docs/src/starknet/index.md
> +### Arguments and Calldata
How about we change this section to `### Arguments` and explain only how to use `--arguments` flag.

Below, we can add a section `### Using Serialized Calldata` and keep the docs for `--calldata`.

2024-11-20 12:04 UTC, cptartur commented on docs/src/starknet/index.md
>  To obtain the serialized form of the wished data, one must write a Cairo program calling `Serde::serialize` on subsequent arguments and displaying the results.
This is outdated, serialized is no longer default - there is no default in code at all.

2024-11-21 11:15 UTC, franciszekjob reviewed
These examples (snippets + outputs) rely on example contract(s) present in our code, right?

2024-11-21 11:15 UTC, franciszekjob commented on docs/src/starknet/index.md
> +
```suggestion

### Using Serialized Calldata

The same result can be achieved by passing serialized calldata, which is a list of hexadecimal-encoded field elements.

For example, this is equivalent to using the --calldata option with the following value: 0x0 0x43686172697a617264  0x9.

To obtain the serialized form of the wished data, you can write a Cairo program that calls `Serde::serialize` on subsequent arguments and displays the results.

Read more about it in the [Cairo documentation](https://book.cairo-lang.org/appendix-03-derivable-traits.html?highlight=seri#serializing-with-serde).

```

2024-11-22 11:55 UTC, cptartur approved these changes

2024-11-22 11:55 UTC, cptartur commented on docs/src/starknet/index.md
> +For example, this is equivalent to using the --calldata option with the following value: 0x0 0x43686172697a617264  0x9.
```suggestion
For example, this is equivalent to using the --calldata option with the following value: 0x0 0x43686172697a617264 0x9.
```

2024-11-22 11:55 UTC, cptartur commented on docs/src/starknet/index.md
> +To obtain the serialized form of the wished data, you can write a Cairo program that calls `Serde::serialize` on subsequent arguments and displays the results.
Kind of resolves https://github.com/foundry-rs/starknet-foundry/issues/2650 but I think we might want to expand this in a separate PR anyway.

2024-11-25 12:11 UTC, merged