Prefix phantom package name
foundry-rs/starknet-foundry pull request #309
Opened 2023-07-27 11:37 UTC by piotmag769

## Introduced changes

Prefix phantom package name created when compiling test files outside of the package folder to avoid name collision with corelib

## Breaking changes

## Checklist

- [ ] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [ ] Performed self-review of the code

2023-07-27 12:19 UTC, Arcticae requested changes
I like that it's fixing this but i feel like we could think of a way without copying the original code, has this been considered?

2023-07-27 12:19 UTC, Arcticae commented on starknet-foundry/crates/test-collector/src/project.rs
> +pub const PHANTOM_PACKAGE_NAME_PREFIX: &str = "forgor";
Please change it to a reasonable name

2023-07-27 12:19 UTC, Arcticae commented on starknet-foundry/crates/test-collector/src/project.rs
> +// COPIED FROM CAIRO COMPILER
If sourcing a file like that, it'd be useful if you provided the original path/lines

2023-07-27 12:19 UTC, Arcticae commented on starknet-foundry/crates/test-collector/src/project.rs
> +        // MODIFIED
Please use 
```
// region: Modified code
// endregion
```
So that IDEs can parse it

2023-07-27 12:19 UTC, Arcticae commented on starknet-foundry/crates/test-collector/src/project.rs
Can't we modify file names instead? And use TMP_DIR if a project is i.e. using files with colliding names only?

2023-07-27 12:24 UTC, Radinyn commented on starknet-foundry/crates/test-collector/src/project.rs
> +pub const PHANTOM_PACKAGE_NAME_PREFIX: &str = "forgor";
rember

2023-07-28 08:37 UTC, Radinyn approved these changes

2023-07-28 10:03 UTC, piotmag769 commented
https://github.com/foundry-rs/starknet-foundry/issues/322

2023-07-28 10:06 UTC, Arcticae approved these changes

2023-07-28 10:24 UTC, merged