Add roll docs, stop_prank docs
foundry-rs/starknet-foundry pull request #351
Opened 2023-07-31 12:56 UTC by MaksymilianDemitraszek

Closes #272 

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code

2023-07-31 13:27 UTC, war-in commented on docs/src/appendix/forge-library/start_roll.md
> +We can use roll in a test to change
```suggestion
We can use `start_roll` to change the current block number inside a test
```

2023-08-01 08:47 UTC, MaksymilianDemitraszek commented
@THenry14 @war-in Yea I should have re-read this, pushing 5 min before end of the day always end like this, sorry :p

2023-08-01 10:06 UTC, piotmag769 requested changes
Can we add it to the index though? It is not displayed anywhere xD

2023-08-01 10:43 UTC, cptartur commented
Taking over this one

2023-08-01 12:17 UTC, piotmag769 commented on docs/src/appendix/cheatcodes/stop_prank.md
> +Cancels the [`stop_prank`](./stop_prank.md) for the contract at the given address.
It's a separate cheatcode

2023-08-01 12:21 UTC, piotmag769 commented on docs/src/appendix/cheatcodes/stop_prank.md
> +Cancels the [`stop_prank`](./stop_prank.md) for the contract at the given address.
Yea, sure xD mb

2023-08-01 12:24 UTC, cptartur commented on docs/src/appendix/cheatcodes/stop_prank.md
> +Cancels the [`stop_prank`](./stop_prank.md) for the contract at the given address.
Yes, fixed

2023-08-01 12:25 UTC, THenry14 approved these changes

2023-08-01 12:28 UTC, piotmag769 commented on docs/src/appendix/cheatcodes/start_prank.md
> +This change can be canceled with [`stop_prank](./stop_prank.md).
Missing "`"

2023-08-01 12:28 UTC, piotmag769 commented on docs/src/appendix/cheatcodes/start_roll.md
> +    fn get_block_number(ref self: ContractState) -> u64 {
getter doesn't require self to be mutable
```suggestion
    fn get_block_number(self: @ContractState) -> u64 {
```

2023-08-01 12:28 UTC, piotmag769 commented on docs/src/appendix/cheatcodes/start_prank.md
> +    fn get_caller_address( ref self: ContractState) -> ContractAddress {
getter doesn't require self to be mutable
```suggestion
    fn get_caller_address(self: @ContractState) -> ContractAddress {
```

2023-08-01 12:48 UTC, piotmag769 approved these changes

2023-08-01 14:16 UTC, merged