Contract verify impl
foundry-rs/starknet-foundry pull request #875
Opened 2023-10-12 14:35 UTC by rjnrohit

Closes #

## Introduced changes

-
-

## Breaking changes

## Checklist

- [ ] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [ ] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

2023-10-17 08:31 UTC, drknzz reviewed
Looks good 👍 could we have some tests for it?
Also, let's add later a mention in the docs and CHANGELOG.md about it

2023-10-17 08:33 UTC, rjnrohit commented on crates/cast/src/starknet_commands/verify.rs
> +    };
This is just a dummy response for now until the voyager APIs become healthy.

2023-10-17 08:40 UTC, rjnrohit commented on crates/cast/src/starknet_commands/verify.rs
> +#[command(about = "Verify a contract through a block exporer")]
fixed, thanks!

2023-10-17 08:41 UTC, rjnrohit commented on crates/cast/src/starknet_commands/verify.rs
> +    pub verifier: String,
Added, thanks 🙂

2023-10-17 08:41 UTC, rjnrohit commented on crates/cast/src/starknet_commands/verify.rs
> +    };
done, thank you :)

2023-10-17 08:41 UTC, rjnrohit commented on crates/cast/src/starknet_commands/verify.rs
> +    pub network: String,
done, thanks you:)

2023-10-17 08:42 UTC, rjnrohit commented
> Looks good 👍 could we have some tests for it? Also, let's add later a mention in the docs and CHANGELOG.md about it

Will add tests when voyager APIs will become healthy and functional

2023-10-18 14:36 UTC, stranger80 approved these changes
LGTM, we now wait until Voyager Verififcation APIs are available for integration test.

2023-10-23 09:26 UTC, THenry14 requested changes
The code's looking very good, thank for the contribution 🔥 

A couple of things though:

Do you think it is in any way test-able? It would be cool to have any form of tests (even with mocks), this would make maintaining this code a lot easier 🙏 

Can you also add an info about this addition to CHANGELOG.md, and update the docs as well, please? There should be [appendix](https://github.com/foundry-rs/starknet-foundry/tree/master/docs/src/appendix/cast) and some [general overview with examples](https://github.com/foundry-rs/starknet-foundry/tree/master/docs/src/starknet) added for `verify`. Thanks!

2024-07-03 19:09 UTC, closed without merging